[package]
name = "day9"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
maplit = "1.0.2"
nalgebra = "0.31.4"
